apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-git-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/MariemRaddaoui/Deploiement
  secretRef:
    name: flux-system # Secret qui contient l'accès au dépôt Git
